# Generated by Django 3.1.4 on 2020-12-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmore',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teachermore',
            name='user',
        ),
    ]
