# Generated by Django 3.1.4 on 2020-12-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_auto_20201222_1204'),
        ('accounts', '0002_auto_20201222_1204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentMore',
        ),
        migrations.DeleteModel(
            name='TeacherMore',
        ),
    ]
