# Generated by Django 3.1.4 on 2020-12-30 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201222_1204'),
        ('test', '0003_auto_20201222_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='test.closedquestion'),
        ),
        migrations.AlterField(
            model_name='closedquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closedQuestions', to='test.test'),
        ),
        migrations.AlterField(
            model_name='cqanswer',
            name='testAnswer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CQAnswers', to='test.testanswer'),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openQuestions', to='test.test'),
        ),
        migrations.AlterField(
            model_name='oqanswer',
            name='testAnswer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OQAnswers', to='test.testanswer'),
        ),
        migrations.AlterField(
            model_name='test',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='accounts.teacher'),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testAnswers', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='testAnswers', to='test.test'),
        ),
    ]
